default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: initapp_development

test:
  <<: *default
  database: initapp_test

production:
  url: <%= ENV.fetch("DATABASE_URL") %>